name: Check Go project

on:
  push:
    branches:
      - main
      - develop
      - issues/*
  pull_request:
    branches:
      - main
      - develop
      - issues/*

jobs:
  build:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./src
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.19'
    - name: Create .env file
      run: cp .env.example .env
    - name: Format check
      run: gofmt -w . && git diff --exit-code
    - name: Build
      run: go build -v -o a.out
    - name: Test
      run: go test -v
