name: Test Go project

on:
  push:
    branches:
      - main
      - develop
      - issues/*
  pull_request:
    branches:
      - main
      - develop
      - issues/*

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.19'
    - name: Build
      run: go build -v -o a.out
    - name: Test
      run: go test -v ./...
